import { VercelRequest, VercelResponse } from '@vercel/node';
import nodemailer from 'nodemailer';

export default async function handler(
  request: VercelRequest,
  response: VercelResponse
) {
  if (request.method !== 'POST') {
    return response.status(405).json({ error: 'Method not allowed' });
  }

  const { name, email, mobile, purpose, message } = request.body;

  // Basic validation
  if (!name || !email || !message) {
    return response.status(400).json({ error: 'Missing required fields' });
  }

  // Configure Nodemailer transporter
  // These variables must be set in Vercel Environment Variables or .env file locally
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT) || 587,
    secure: process.env.SMTP_SECURE === 'true', // true for port 465, false for other ports
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  try {
    // Send mail with defined transport object
    await transporter.sendMail({
      from: `"${name}" <${process.env.SMTP_USER}>`,
      to: process.env.RECIPIENT_EMAIL,
      replyTo: email,
      subject: `GENZ Neural X Lead: ${purpose || 'New Inquiry'} from ${name}`,
      text: `New lead from ${name} (${email}). Message: ${message}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #000; color: #ffffff; margin: 0; padding: 0; }
            .container { max-width: 600px; margin: 0 auto; background-color: #0a0a0a; border: 1px solid #1a1a1a; }
            .header { padding: 40px; text-align: center; border-bottom: 1px solid #1a1a1a; }
            .logo { font-size: 24px; font-weight: 900; letter-spacing: 5px; color: #ffffff; text-transform: uppercase; margin: 0; }
            .accent { color: #a855f7; }
            .content { padding: 40px; }
            .heading { font-size: 20px; font-weight: 900; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 30px; border-left: 4px solid #a855f7; padding-left: 20px; }
            .field { margin-bottom: 25px; }
            .label { font-size: 10px; font-weight: 900; color: rgba(255,255,255,0.4); text-transform: uppercase; letter-spacing: 2px; margin-bottom: 5px; }
            .value { font-size: 16px; color: #ffffff; }
            .message-box { background-color: #111; padding: 25px; border-radius: 12px; border: 1px solid #222; margin-top: 10px; line-height: 1.6; }
            .footer { padding: 30px; text-align: center; font-size: 11px; color: rgba(255,255,255,0.2); border-top: 1px solid #1a1a1a; text-transform: uppercase; letter-spacing: 2px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1 class="logo">GENZ<span class="accent"> Neural X</span></h1>
            </div>
            <div class="content">
              <div class="heading">New Lead Transmission</div>
              
              <div class="field">
                <div class="label">Client Name</div>
                <div class="value">${name}</div>
              </div>

              <div class="field">
                <div class="label">Email Address</div>
                <div class="value">${email}</div>
              </div>

              <div class="field">
                <div class="label">Mobile Number</div>
                <div class="value">${mobile || 'Not Provided'}</div>
              </div>

              <div class="field">
                <div class="label">Purpose / Subject</div>
                <div class="value">${purpose || 'General Inquiry'}</div>
              </div>

              <div class="field">
                <div class="label">Message Content</div>
                <div class="message-box">
                  ${message.replace(/\n/g, '<br/>')}
                </div>
              </div>
            </div>
            <div class="footer">
              Generated by GENZ Neural X Systems &copy; 2026
            </div>
          </div>
        </body>
        </html>
      `,
    });

    return response.status(200).json({ success: true });
  } catch (error) {
    console.error('Email send error:', error);
    return response.status(500).json({ error: 'Failed to send email' });
  }
}
